version: '3.8'

services:
  mongodb:
    image: mongo:7.0-jammy
    container_name: mongodb
    ports:
      - "27017:27017" # Let's change it back to the standard 27017
    volumes:
      - mongo_data:/data/db # <--- Use a named volume here
    restart: always

volumes:
  mongo_data: # <--- Define the volume here at the bottom
